CREATE TABLE IF NOT EXISTS "productos" (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sku text,
  content_hash text,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  proteccion_uv text,
  resistencia_intemperie text,
  apilable text,
  brazos text,
  soporte_lumbar text,
  cabecera text,
  uso_recomendado text,
  source_id integer,
  source_row_key text,
  last_synced_at timestamptz,
  sync_metadata jsonb,
  producto_id text,
  producto text,
  categoria text,
  descripcion text,
  url_producto text,
  id_catalogo text,
  pagina_catalogo text,
  color text,
  precio_usd numeric,
  material text,
  tapizado text,
  estructura text,
  ancho_total_cm numeric,
  profundidad_asiento_cm numeric,
  altura_total_cm numeric,
  altura_asiento_cm numeric,
  ancho_asiento_cm numeric,
  peso_kg numeric,
  mecanismo text,
  especificaciones_adicionales text,
  estado_validacion text,
  observaciones_cliente text
);

TRUNCATE TABLE "productos" RESTART IDENTITY;

INSERT INTO "productos"
  (sku, is_active, source_row_key, producto_id, producto, categoria, descripcion, url_producto, color,
   precio_usd, uso_recomendado, especificaciones_adicionales, estado_validacion,
   material, tapizado, estructura, ancho_total_cm, profundidad_asiento_cm, altura_total_cm,
   altura_asiento_cm, ancho_asiento_cm, peso_kg, mecanismo)
VALUES
  ('SKU-0001', true, 'row-1', 'ALT-P-0001', 'La silla Oliva', 'Sillas Tapizadas',
   'Silla tapizada en tono verde oliva con estructura metálica.', 'https://altosa.example/products/oliva',
   'Verde Oliva', 110.00, 'Oficina;Comedor', 'Tapizado premium;Patas metálicas', 'Aprobado',
   'Acero', 'Tela', 'Metálica', 56, 48, 82, 46, 45, 6.2, 'Fijo'),
  ('SKU-0001-B', true, 'row-2', 'ALT-P-0001', 'La silla Oliva', 'Sillas Tapizadas',
   'Silla tapizada en tono verde oliva con estructura metálica.', 'https://altosa.example/products/oliva',
   'Mostaza', 115.00, 'Oficina;Comedor', 'Tapizado premium;Patas metálicas', 'Aprobado',
   'Acero', 'Tela', 'Metálica', 56, 48, 82, 46, 45, 6.2, 'Fijo'),
  ('SKU-0001-C', true, 'row-3', 'ALT-P-0001', 'La silla Oliva', 'Sillas Tapizadas',
   'Silla tapizada en tono verde oliva con estructura metálica.', 'https://altosa.example/products/oliva',
   'Gris', 110.00, 'Oficina;Comedor', 'Tapizado premium;Patas metálicas', 'Aprobado',
   'Acero', 'Tela', 'Metálica', 56, 48, 82, 46, 45, 6.2, 'Fijo'),
  ('SKU-0002', true, 'row-4', 'ALT-P-0002', 'Silla Sandy', 'Sillas Tapizadas',
   'Silla ergonómica con soporte lumbar anatómico.', 'https://altosa.example/products/sandy',
   'Taupe', 95.50, 'Oficina;Home office', 'Soporte lumbar', 'Pendiente',
   'Acero', 'Tela', 'Metálica', 58, 50, 84, 47, 46, 7.1, 'Reclinable'),
  ('SKU-0003', true, 'row-5', 'ALT-P-0003', 'Silla Plástica Mónaco', 'Sillas de Plastico',
   'Silla monobloque de polipropileno para exteriores.', 'https://altosa.example/products/monaco',
   'Blanco', 25.50, 'Exteriores;Eventos', 'Resistente a UV', 'Aprobado',
   'Polipropileno', NULL, 'Monobloque', 45, 42, 80, 44, 42, 3.4, NULL),
  ('SKU-0003-B', true, 'row-6', 'ALT-P-0003', 'Silla Plástica Mónaco', 'Sillas de Plastico',
   'Silla monobloque de polipropileno para exteriores.', 'https://altosa.example/products/monaco',
   'Negro', 25.50, 'Exteriores;Eventos', 'Resistente a UV', 'Aprobado',
   'Polipropileno', NULL, 'Monobloque', 45, 42, 80, 44, 42, 3.4, NULL),
  ('SKU-0004', true, 'row-7', 'ALT-P-0004', 'Mesa Auxiliar Nórdica', 'Bases y mesas',
   'Mesa auxiliar con base metálica y tapa de madera.', 'https://altosa.example/products/nordica',
   'Roble', 180.00, 'Sala;Recibidor', 'Tapa 60cm', 'Requiere corrección',
   'Madera', NULL, 'Metálica', 60, NULL, 45, NULL, NULL, 9.5, NULL),
  ('SKU-0005', true, 'row-8', 'ALT-P-0005', 'Taburete Alto Bari', 'Taburetes',
   'Taburete alto con asiento acolchado.', NULL,
   'Negro', NULL, 'Barra;Cocina', NULL, NULL,
   'Acero', 'Cuero sintético', 'Metálica', 40, 40, 75, 65, 38, 5.8, NULL),
  ('SKU-0006', true, 'row-9', 'ALT-P-0006', 'Silla Ergonómica Praga', 'Sillas de Oficina',
   'Silla operativa con soporte lumbar ajustable.', 'https://altosa.example/products/praga',
   'Gris', 210.75, 'Oficina;Ergonomía', 'Ruedas de silicona', 'Aprobado',
   'Acero', 'Malla', 'Metálica', 60, 52, 90, 48, 47, 8.3, 'Sincronizado'),
  ('SKU-0006-B', false, 'row-10', 'ALT-P-0006', 'Silla Ergonómica Praga', 'Sillas de Oficina',
   'Variante descontinuada.', 'https://altosa.example/products/praga',
   'Rojo', 199.00, 'Oficina', NULL, 'Pendiente',
   'Acero', 'Malla', 'Metálica', 60, 52, 90, 48, 47, 8.3, 'Sincronizado');
